workspaces:
  use:
    - objc-binaries

script: ./a.out

jobs:
  include:
    - stage: Build on 10.14
      os: osx
      osx_image: xcode10.3
      workspaces:
        create:
          name: objc-binaries
          paths:
            - a.out
      script: export MACOSX_DEPLOYMENT_TARGET=10.11 && clang -fobjc-arc objc.m

    - stage: Run on older versions of macOS
      os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode8.3

    - os: osx
      osx_image: xcode7.3
